# version: '3.8'
# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   backend_colmed_coy:
#     build: .
#     volumes:
#       - .:/app
#     ports:
#       - "8001:8000"
#     environment:
#       - DB_NAME=${DB_NAME}
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_HOST=db
#       - DB_PORT=${DB_PORT}
#     env_file:
#       - .env
#     depends_on:
#       - db

# volumes:
#   postgres_data:


############### VERSION PREVIA ################
version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
    volumes:
      - .:/app
      - /app/static
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
