# Generated by Django 5.0.6 on 2025-06-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaMedicoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('habitaciones', models.JSONField(blank=True, default=list)),
                ('detalles', models.JSONField(blank=True, default=list)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColegiarseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quienesTitulo', models.CharField(blank=True, max_length=255)),
                ('quienes', models.TextField(blank=True)),
                ('comoTitulo', models.CharField(blank=True, max_length=255)),
                ('procedimiento', models.TextField(blank=True)),
                ('linkInscripcion', models.URLField(blank=True)),
                ('infoPreviaTitulo', models.CharField(blank=True, max_length=255)),
                ('documentos', models.TextField(blank=True)),
                ('medicosChileTitulo', models.CharField(blank=True, max_length=255)),
                ('medicosChileContenido', models.TextField(blank=True)),
                ('medicosExtranjeroTitulo', models.CharField(blank=True, max_length=255)),
                ('medicosExtranjeroContenido', models.TextField(blank=True)),
                ('queHaceTitulo', models.CharField(blank=True, max_length=255)),
                ('queHaceContenido', models.TextField(blank=True)),
                ('porqueTitulo', models.CharField(blank=True, max_length=255)),
                ('porqueContenido', models.TextField(blank=True)),
                ('deberesTitulo', models.CharField(blank=True, max_length=255)),
                ('deberesContenido', models.TextField(blank=True)),
                ('derechosContenido', models.TextField(blank=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('descripcion_general', models.TextField(blank=True)),
                ('detalle_cuotas', models.TextField(blank=True)),
                ('notas', models.JSONField(blank=True, default=list)),
                ('tipos_cuotas', models.JSONField(blank=True, default=list)),
                ('valores_cuotas', models.JSONField(blank=True, default=list)),
                ('detalle_fsg', models.JSONField(blank=True, default=list)),
                ('reafiliacion_titulo', models.CharField(blank=True, max_length=255)),
                ('reafiliacion_descripcion', models.TextField(blank=True)),
                ('valores_reafiliacion', models.JSONField(blank=True, default=list)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
