# Generated by Django 5.0.6 on 2025-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0002_casamedicoinfo_colegiarseinfo_paymentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='detalle_fsg',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='notas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='tipos_cuotas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='valores_cuotas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='valores_reafiliacion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
