# Generated by Django 5.0.6 on 2025-07-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0003_alter_paymentinfo_detalle_fsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casamedicoinfo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casamedicoinfo',
            name='detalles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='casamedicoinfo',
            name='habitaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
