# Generated by Django 5.0.6 on 2025-07-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0004_alter_casamedicoinfo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misionvision',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misionvision',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
