# Generated by Django 5.0.6 on 2025-07-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0006_alter_agrupacionregional_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunalmember',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directiva', to='base_toolbar.tribunaletica'),
        ),
    ]
