# Generated by Django 5.0.6 on 2025-07-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0007_alter_tribunalmember_tribunal'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='link2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='colegiarseinfo',
            name='linkInscripcion2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='normativaitem',
            name='link2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='colegiarseinfo',
            name='linkInscripcion',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
