# Generated by Django 5.0.6 on 2025-07-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0008_capitulo_link2_colegiarseinfo_linkinscripcion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='link',
        ),
        migrations.RemoveField(
            model_name='colegiarseinfo',
            name='linkInscripcion',
        ),
        migrations.RemoveField(
            model_name='normativaitem',
            name='link',
        ),
    ]
