# Generated by Django 5.0.6 on 2025-07-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_toolbar', '0009_remove_capitulo_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitulo',
            old_name='link2',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='colegiarseinfo',
            old_name='linkInscripcion2',
            new_name='linkInscripcion',
        ),
        migrations.RenameField(
            model_name='normativaitem',
            old_name='link2',
            new_name='link',
        ),
    ]
