# Generated by Django 5.0.6 on 2024-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumen_contenido',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
