# Generated by Django 5.0.6 on 2024-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estamento', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_estamento', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_estamento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LugarDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='plaza',
            name='codigo',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
