# Generated by Django 5.0.6 on 2024-10-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0002_entidad_estamento_lugardescuento_alter_plaza_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='sigla',
            field=models.CharField(default='', max_length=50),
        ),
    ]
