# Generated by Django 5.0.6 on 2024-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0003_entidad_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre_entidad',
            field=models.CharField(max_length=100),
        ),
    ]
