# Generated by Django 5.0.6 on 2024-10-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0005_beneficio_titulo_alter_beneficio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
