# Generated by Django 5.0.6 on 2024-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0006_alter_beneficio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
