# Generated by Django 5.0.6 on 2025-01-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0008_alter_perfil_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('admin_noticias', 'Administrador Noticias'), ('admin_colmed', 'Administrador Colmed'), ('gestor_informatico', 'Gestor Informático'), ('admin_eventos', 'Administrador de Eventos'), ('admin_sitio', 'Administrador del Sitio')], default='visitante', max_length=50),
        ),
        migrations.CreateModel(
            name='PublicidadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('link', models.TextField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades_medicas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
