# Generated by Django 5.0.6 on 2025-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0009_alter_perfil_tipo_perfil_publicidadmedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('admin_noticias', 'Administrador Noticias'), ('admin_colmed', 'Administrador Colmed'), ('gestor_informatico', 'Gestor Informático'), ('admin_eventos', 'Administrador de Eventos y Comunicaciones'), ('admin_sitio', 'Administrador del Sitio')], default='visitante', max_length=50),
        ),
    ]
