# Generated by Django 5.0.6 on 2025-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0010_alter_evento_fecha_fin_alter_evento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_evento_google',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
