# Generated by Django 5.0.6 on 2025-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0011_alter_evento_id_evento_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
