# Generated by Django 5.0.6 on 2025-03-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0012_evento_privado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional')], max_length=20)),
                ('ref', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConveniosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos_convenios_link', models.URLField(blank=True, help_text="URL para 'Todos los convenios'", null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Convenios',
                'verbose_name_plural': 'Configuraciones de Convenios',
            },
        ),
    ]
