# Generated by Django 5.0.6 on 2025-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0014_evento_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contacto de Interés',
                'verbose_name_plural': 'Contactos de Interés',
            },
        ),
        migrations.CreateModel(
            name='LinkInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Link de Interés',
                'verbose_name_plural': 'Links de Interés',
                'ordering': ['orden'],
            },
        ),
    ]
