# Generated by Django 5.0.6 on 2025-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0015_contactointeres_linkinteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactointeres',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
