# Generated by Django 5.0.6 on 2025-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0016_contactointeres_privado'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinteres',
            name='clave',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
