# Generated by Django 5.0.6 on 2025-06-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0017_linkinteres_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinteres',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
