# Generated by Django 5.0.6 on 2025-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0018_linkinteres_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinteres',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
