# Generated by Django 5.0.6 on 2025-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0019_alter_linkinteres_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactointeres',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
