# Generated by Django 5.0.6 on 2025-06-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0020_alter_contactointeres_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactointeres',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
