# Generated by Django 5.0.6 on 2025-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0025_alter_contactointeres_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactointeres',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
