# Generated by Django 5.0.6 on 2025-07-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0026_contactointeres_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactointeres',
            name='email',
        ),
    ]
