# Generated by Django 5.0.6 on 2025-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0027_remove_contactointeres_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactointeres',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
