# Generated by Django 5.0.6 on 2025-07-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0028_contactointeres_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactointeres',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactointeres',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
