# Generated by Django 5.0.6 on 2025-07-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0029_alter_contactointeres_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAppColmedChile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Link App Colmed Chile',
                'verbose_name_plural': 'Links App Colmed Chile',
            },
        ),
    ]
