# Generated by Django 5.0.6 on 2024-08-13 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=255)),
                ('icm', models.BigIntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_titulo', models.DateField()),
                ('moroso', models.BooleanField(blank=True, null=True)),
                ('cuotas_totales', models.BigIntegerField(blank=True, null=True)),
                ('registro_superintendencia', models.BigIntegerField()),
                ('rut', models.CharField(max_length=255)),
                ('directiva', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_medicos.medico')),
            ],
        ),
    ]
