# Generated by Django 5.0.6 on 2024-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='condicion_vital',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
