# Generated by Django 5.0.6 on 2024-09-25 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0001_initial'),
        ('base_medicos', '0002_medico_condicion_vital_alter_medico_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_colmed.plaza'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_titulo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='icm',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro_superintendencia',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
