# Generated by Django 5.0.6 on 2024-09-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0003_medico_plaza_alter_medico_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_inscripcion_col',
            field=models.DateField(blank=True, null=True),
        ),
    ]
