# Generated by Django 5.0.6 on 2024-10-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_colmed', '0002_entidad_estamento_lugardescuento_alter_plaza_codigo'),
        ('base_medicos', '0004_medico_direccion_medico_fecha_inscripcion_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='cuotas_totales',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='fecha_inscripcion_col',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='moroso',
        ),
        migrations.AddField(
            model_name='medico',
            name='regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_socio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pago', models.CharField(choices=[('al_dia', 'Al día'), ('moroso', 'Moroso'), ('moroso12', 'Moroso12'), ('liberado', 'Liberado'), ('casado_medico', 'Casado con Médico'), ('falmed_senior_liberado', 'FALMED Senior Liberado'), ('liberado_rescate', 'Liberado por Rescate'), ('liberado_directorio_falmed', 'Liberado Directorio Falmed'), ('recien_inscrito', 'Recién Inscrito'), ('no_informado', 'No informado')], default='no_informado', max_length=50)),
                ('anio_ucp', models.IntegerField(blank=True, null=True)),
                ('mes_ucp', models.IntegerField(blank=True, null=True)),
                ('num_ultima_cuota', models.IntegerField(blank=True, null=True)),
                ('fecha_ultima_cuota', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_colmed.entidad')),
                ('estamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_colmed.estamento')),
                ('lugar_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_colmed.lugardescuento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_medicos.medico')),
            ],
        ),
    ]
