# Generated by Django 5.0.6 on 2024-10-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0005_remove_medico_cuotas_totales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliacion',
            name='codigo_socio',
        ),
        migrations.RemoveField(
            model_name='afiliacion',
            name='fecha_ultima_cuota',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='regional',
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='condicion_afiliado',
            field=models.CharField(choices=[('afiliado', 'AFILIADO'), ('afiliado_pendiente', 'AFILIADO PENDIENTE'), ('condecoracion_honor', 'CONDECORACION DE HONOR'), ('desafiliado', 'DESAFILIADO'), ('renunciado', 'RENUNCIADO'), ('renunciado_dir', 'RENUNCIADO DIR'), ('expulsado', 'EXPULSADO'), ('inscripcion_rechazada', 'INSCRIPCION RECHAZADA'), ('no_inscrito', 'NO INSCRITO'), ('reaf_pend_aprob_mesa', 'REAF. PEND. APROB. MESA'), ('reaf_pend_aprob_smrio_etico', 'REN. PEND. APRB. SMRIO. ETICO'), ('reafiliacion_rechazada', 'REAFILIACION RECHAZADA'), ('reinscrito', 'REINSCRITO'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=50),
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='tipo_cuota',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='comuna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='afiliacion',
            name='estado_pago',
            field=models.CharField(choices=[('al_dia', 'AL DIA'), ('moroso', 'MOROSO'), ('moroso12', 'MOROSO12'), ('liberado', 'LIBERADO'), ('casado_medico', 'CASADO CON MEDICO'), ('falmed_senior_liberado', 'FALMED SENIOR LIBERADO'), ('liberado_rescate', 'LIBERADO POR RESCATE'), ('liberado_directorio_falmed', 'LIBERADO DIRECTORIO FALMED'), ('recien_inscrito', 'RECIEN INSCRITO'), ('proceso_a_desafiliar', 'PROCESO A DESAFILIAR'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rut',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
