# Generated by Django 5.0.6 on 2024-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0006_remove_afiliacion_codigo_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='directiva',
            field=models.CharField(blank=True, choices=[('presidente', 'Presidente'), ('presidenta', 'Presidenta'), ('vicepresidente', 'VicePresidente'), ('vicepresidenta', 'VicePresidenta'), ('secretaria', 'Secretaria'), ('secretario', 'Secretario'), ('tesorera', 'Tesorera'), ('tesorero', 'Tesorero'), ('consejero', 'Consejero'), ('consejera', 'Consejera'), ('', '------')], default='', max_length=255, null=True),
        ),
    ]
