# Generated by Django 5.0.6 on 2024-12-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0007_alter_medico_directiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField()),
                ('institucion_certificadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institucion', to='base_medicos.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSuperintendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=20, unique=True)),
                ('fecha_registro', models.DateField()),
                ('codigo_validacion', models.CharField(max_length=50, unique=True)),
                ('titulo_profesional', models.CharField(max_length=255)),
                ('fecha_titulo', models.DateField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(related_name='especialidades', to='base_medicos.especialidad')),
                ('universidad_titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universidad', to='base_medicos.institucion')),
            ],
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro_superintendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_medicos.registrosuperintendencia'),
        ),
    ]
