# Generated by Django 5.0.6 on 2024-12-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0008_institucion_especialidad_registrosuperintendencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='registro_superintendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_superintendencia', to='base_medicos.registrosuperintendencia'),
        ),
    ]
