# Generated by Django 5.0.6 on 2024-12-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0009_alter_medico_registro_superintendencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='registro_superintendencia',
            new_name='registro_superintendencia_b',
        ),
    ]
