# Generated by Django 5.0.6 on 2024-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0010_rename_registro_superintendencia_medico_registro_superintendencia_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='registro_superintendencia',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
