# Generated by Django 5.0.6 on 2024-12-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0011_medico_registro_superintendencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='registro_superintendencia_b',
        ),
    ]
