# Generated by Django 5.0.6 on 2024-12-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0012_remove_medico_registro_superintendencia_b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='registro_superintendencia',
            new_name='registro',
        ),
        migrations.AddField(
            model_name='medico',
            name='registro_superintendencia_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_superintendencia', to='base_medicos.registrosuperintendencia'),
        ),
    ]
