# Generated by Django 5.0.6 on 2024-12-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0014_rename_registro_superintendencia_b_medico_registro_superintendencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosuperintendencia',
            name='fecha_titulo',
        ),
        migrations.RemoveField(
            model_name='registrosuperintendencia',
            name='titulo_profesional',
        ),
        migrations.RemoveField(
            model_name='registrosuperintendencia',
            name='universidad_titulo',
        ),
        migrations.CreateModel(
            name='OrdenProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField()),
                ('institucion_certificadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universidad', to='base_medicos.institucion')),
            ],
        ),
        migrations.AddField(
            model_name='registrosuperintendencia',
            name='ordenes_profesionales',
            field=models.ManyToManyField(related_name='ordenes_profesionales', to='base_medicos.ordenprofesional'),
        ),
    ]
