# Generated by Django 5.0.6 on 2024-12-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0015_remove_registrosuperintendencia_fecha_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosuperintendencia',
            name='codigo_validacion',
        ),
        migrations.AddField(
            model_name='registrosuperintendencia',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrosuperintendencia',
            name='nacionalidad',
            field=models.CharField(default='', max_length=20),
        ),
    ]
