# Generated by Django 5.0.6 on 2025-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0017_medicoappmovil_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoappmovil',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
