# Generated by Django 5.0.6 on 2025-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0018_medicoappmovil_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoappmovil',
            name='apple_sub',
            field=models.CharField(blank=True, db_index=True, help_text="Identificador 'sub' de Sign\u202fin\u202fwith\u202fApple", max_length=164, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medicoappmovil',
            name='cuenta_activa',
            field=models.BooleanField(default=False),
        ),
    ]
