# Generated by Django 5.0.6 on 2025-07-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0019_medicoappmovil_apple_sub_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicoappmovil',
            old_name='fecha_inscripcion',
            new_name='fecha_actualizacion',
        ),
    ]
