# Generated by Django 5.0.6 on 2025-07-26 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0020_rename_fecha_inscripcion_medicoappmovil_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoappmovil',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
