# Generated by Django 5.0.6 on 2025-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_medicos', '0021_medicoappmovil_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicoappmovil',
            name='apple_sub',
            field=models.CharField(blank=True, db_index=True, help_text="Identificador 'sub' de Sign\u202fin\u202fwith\u202fApple", max_length=255, null=True, unique=True),
        ),
    ]
